### ISSUE TITLE
gr-dab for gnuradio 3.7

### ISSUE THREAD

**Issue by kayvax** [andrmuel/gr-dab#1]
Hi,
I have tried to compile gr-dab block and there is configure problem as it is looking for gr-core module of gnuradio. With gnuradio 3.7 there was redesign of modules thus there is no gr-core.

Is there a glipse o hope to see this block updated to gnuradio 3.7 specs?

**Comment by rubund** [comment]
Pull request made ;)

**Comment by andrmuel** [comment]
It actually compiles again, thank you.

Therefore closing this issue.
