### ISSUE TITLE
DAB+ receipt on macbook

### ISSUE THREAD

**Issue by adamkk** [andrmuel/gr-dab#11]
Hi,

could you help me and prepare a Mac Ports version of DAB+ receiver/transmitter software?

best,
Adam

**Comment by andrmuel** [comment]
Hello Adam

The code is currently not in a state where you can install and use it. At the moment it will only be useful for developers or people who want to experiment with DAB.

Furthermore I do not own a Mac, so in any case I wouldn't be able or willing to help here.

Best regards, Andreas

**Comment by adamkk** [comment]
Hello Andres,

Just found that you can run a Yosemite macosx on a virtual machine. Pls check that link: http://www.macbreaker.com/2015/01/virtualbox-yosemite-zone.html

I have Win7 on my mac, and it is possible to connect a USB dongle to that. Hope that you can do the same with DAB software & hardware.

Wish you luck !!!

Best,
Adam

**Comment by andrmuel** [comment]
Hello Adam

Despite the fact that I don't think a package would be too useful at the moment, I'm also not interested in supporting a proprietary operating system, or any non-free software per se ...

Best regards,
Andreas
