### ISSUE TITLE
GNURadio 3.8 support

### ISSUE THREAD

**Issue by yarda** [andrmuel/gr-dab#24]
GNURadio 3.8 brings Python 3 support. Linux distro's are dropping Python 2 packages, because Python 2 is near EOL. E.g. in Fedora Rawhide (f32) all Python 2 packages without FESCO exception were mass orphaned. GNURadio 3.8 support is needed to keep this package in the distros.

I tried to do some initial (but not optimal) porting, but it's more complex task. I have still problems with the GRC flowgraphs. My initial attempt:
https://jskarvad.fedorapeople.org/gr-dab/gr-dab-0.3-python38.patch

**Comment by yarda** [comment]
I missed it's probably already done :) sorry for noise.

**Comment by rubund** [comment]
I'm sorry to hear that you got some extra work since you didn't see I had already done it. I'm maintaining the official Debian package of gr-dab, so that was the main motivation for porting it a few months ago.

Cheers

**Comment by yarda** [comment]
NP, my fault :) I am maintaining gnuradio and few gr modules in Fedora and I had to port some of them myself in short period of time and this one just got mistakenly to the queue :) I need to be more careful next time. Thanks for the port.
