### ISSUE TITLE
Using DAB with RTL-SDR Source

### ISSUE THREAD

**Issue by Korbinian89** [andrmuel/gr-dab#3]
Hello,

is it possible to use your dab-receiver with a RTL-SDR Source instead of the USRP?

This brings me to my next question, how to use your application? And is it possible to demodulate and listening DAB-Radio in realtime? 

Best regards & thanks in advance

**Comment by andrmuel** [comment]
Hello Korbinian

In the current state, the code is not usable as a stand-alone application, as it implements only the lower layers (physical layer, error correction, etc., but no FIB protocol layer or decoding of audio streams).

The error you are seeing could be related to a non-working peak detector, but I'm afraid I currently don't have the time to take a closer look to find out for sure.

In the current state, the code is likely only useful if you want to work on it ...

Best regards, Andreas

**Comment by Korbinian89** [comment]
Hello Andreas,

thank you for your quick response. I will take a closer look at the peak detector and hope that will fix it for me. I also found your report, which explains everything in detail. That's a very impressive work.  

Best regards, 
Korbinian
