### ISSUE TITLE
Boost required to compile dab

### ISSUE THREAD

**Issue by white-gecko** [andrmuel/gr-dab#7]
I'm trying to build gr-dab on my debian system. On running `cmake ../` I get the following output:

    $ cmake ../
    -- Build type not specified: defaulting to release.
    -- Could NOT find Boost
    CMake Error at CMakeLists.txt:63 (message):
      Boost required to compile dab
    
    
    -- Configuring incomplete, errors occurred!
    See also "[…]/gr-dab/build/CMakeFiles/CMakeOutput.log".

but [libboost-dev](https://packages.debian.org/jessie/libboost-dev) (version 1.55.0.2) is installed. There are some more libboost packages, but which is needed?

**Comment by white-gecko** [comment]
I think this issue is due to the fact, that `pkg-config` can't find libboost on debian GNU/Linux, because there is no .pc file in libboost …

**Comment by andrmuel** [comment]
I have to admit I'm not too familiar with cmake, but on my system, boost is found before cmake, so I would assume that pkg-config is not the issue.

Relevant output on my system:

    -- Build type not specified: defaulting to release.
    -- Boost version: 1.56.0
    -- Found the following Boost libraries:
    --   filesystem
    --   system
    -- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
    -- checking for module 'cppunit'
    [..]

Have you tried adding your exact boost version to `Boost_ADDITIONAL_VERSIONS` in `CMakeLists.txt`?

**Comment by white-gecko** [comment]
Yes, adding the version to `Boost_ADDITIONAL_VERSIONS` doesn't help for me.

**Comment by white-gecko** [comment]
Ah, ok, I had to install `libboost-filesystem*-dev` and  `libboost-system*-dev` as well
