### ISSUE TITLE
Constellation map sometimes get broken

### ISSUE THREAD

**Issue by piratfm** [andrmuel/gr-dab#8]
Hi, I'm using gr-dab module to watch for constellation diagram of the modulated signal. But I found that diagram - is not stable from real hardware.

After that to make sure that module working properly, I used modulator's direct I/Q output as source for decoder. But unfortunaly that won't help. Neither dab_rx_constellation.py (with file input) nor GRC graph works for me:

![grc](https://cloud.githubusercontent.com/assets/1777542/12417477/05fdd35e-beb1-11e5-9033-e197198f9e86.png)

The source file has been generated by ODR-DabMod using commandline:
```odr-dabmod test.dump.eti -g 2 -m 1 -f test.dump.eti.mod.raw```

The problem, that sometimes constellation became broken like this:

![bad_constellation5](https://cloud.githubusercontent.com/assets/1777542/12417692/79b45f2e-beb2-11e5-88fc-48b3e17083f9.png)

Tuning parameters like filtering, equalisation, correcting ffe and samplerate won't help. Anyway they are not needed for direct modulated input, since they are not yet distorted.

**Comment by andrmuel** [comment]
Hi

So if I understand correctly, this signal should be free of noise? I guess that would mean the noise is added internally somewhere. I'm not really sure, how that would happen. Maybe there is clipping somewhere?

**Comment by piratfm** [comment]
Yes, the normal constellation from modulated I/Q file - is just 4 small dots. Here is results before it breaks (also filter and equalizer and samplerate correection is turned off here):
![gr_dab_fine](https://cloud.githubusercontent.com/assets/1777542/12443325/bf52c450-bf5f-11e5-85a6-3c08109657cb.png)

I'm tried to make amplitude in range: -1.0 ... 1.0 but that won't helped.

**Comment by andrmuel** [comment]
Great, thank you for tracking down & fixing it!

I'm not too surprised that sample rate correction is a bit broken. IIRC I never used it much, and I think it shouldn't usually be needed even with real samples (unless for devices with a really bad oscillator).

Btw. magnitude equalization is of course also purely cosmetic, as the information is only in the phase.
